EncodingConverter
std::string EncodingConverter::inputDirectory
Referenced by convert, convertDirectory, convertFile.
std::string EncodingConverter::outputDirectory
Referenced by convertDirectory, convertFile.
bool EncodingConverter::useTempDirectory
Referenced by convertDirectory, convertFile.
std::vector<std::string> EncodingConverter::fileExtensions
Referenced by convertDirectory, loadSettings.
std::string EncodingConverter::sourceEncoding
Referenced by convertFile, loadSettings.
std::string EncodingConverter::targetEncoding
Referenced by convertFile, loadSettings.
size_t EncodingConverter::filesProcessed
Referenced by convertDirectory, EncodingConverter, printStats.
size_t EncodingConverter::filesConverted
Referenced by convertFile, EncodingConverter, printStats.
EncodingConverter::EncodingConverter(std::string inputDir, const std::string &outputDir="")
Конструктор объекта EncodingConverter.
inputDir Входной каталог. outputDir Выходной каталог. Если outputDir пуст, используется временный каталог. Загружает настройки преобразования кодировки и сбрасывает счетчики файлов.
References filesConverted, filesProcessed, loadSettings.
void EncodingConverter::convert()
Конвертирует файлы в директории.
Метод конвертирует файлы в указанной директории и выводит статистику по конвертированным файлам. Путь к директории, содержащей исходные файлы, задается в переменной inputDirectory.
References convertDirectory, inputDirectory, printStats.
Referenced by main.
void EncodingConverter::loadSettings()
Загружает настройки преобразования кодировки.
Устанавливает исходную кодировку в "UTF-8" и целевую кодировку в "WINDOWS-1251". Задает расширения файлов, которые следует преобразовывать.
References fileExtensions, sourceEncoding, targetEncoding.
Referenced by EncodingConverter.
void EncodingConverter::convertDirectory(const std::filesystem::path &dir)
Конвертирует файлы в указанной директории и её поддиректориях.
Метод рекурсивно конвертирует все файлы в указанной директории и её поддиректориях. Конвертируемые файлы должны иметь расширения, указанные в списке fileExtensions. Если файл имеет другое расширение и outputDirectory указана, он будет скопирован в указанную выходную директорию. dir Путь к директории, в которой нужно выполнить конвертацию файлов.
References convertFile, fileExtensions, filesProcessed, inputDirectory, outputDirectory, useTempDirectory.
Referenced by convert.
void EncodingConverter::convertFile(const std::filesystem::path &filepath)
Конвертирует содержимое файла из одной кодировки в другую и сохраняет результат в файл.
Метод читает содержимое файла с указанным путем, конвертирует его из исходной кодировки в целевую и сохраняет результат в файл. Если включена опция useTempDirectory, то промежуточный файл будет создан во временной директории, а затем скопирован и заменит исходный файл. filepath Путь к файлу, который нужно конвертировать.
References filesConverted, iconvConvert, inputDirectory, is_utf8, outputDirectory, sourceEncoding, targetEncoding, useTempDirectory.
Referenced by convertDirectory.
void EncodingConverter::printStats() const
Выводит статистику по конвертированным файлам.
Метод выводит информацию о количестве обработанных и конвертированных файлов.
References filesConverted, filesProcessed.
Referenced by convert.
bool EncodingConverter::iconvConvert(const std::string &input, std::string &output, const std::string &fromCharset, const std::string &toCharset)
Конвертирует строку из одной кодировки в другую с помощью iconv.
Метод конвертирует строку из одной кодировки в другую с использованием функций iconv. input Входная строка для конвертации. output Строка, в которую будет записан результат конвертации. fromCharset Исходная кодировка. toCharset Целевая кодировка. true, если конвертация прошла успешно, иначе false.
Referenced by convertFile.
bool EncodingConverter::is_utf8(const std::string &str)
Проверяет, является ли строка в кодировке UTF-8.
Метод проверяет, является ли строка в кодировке UTF-8 путем анализа байтовой последовательности. Возвращает true, если строка является корректной UTF-8 строкой, иначе false. str Строка, которую нужно проверить. true, если строка является корректной UTF-8 строкой, иначе false.
Referenced by convertFile.