textReader
textReader::textReader(const std::filesystem::path &file_path)
Конструктор класса textReader.
file_path Путь к файлу для чтения. Конструктор инициализирует объект textReader с указанным путем к файлу file_path и вызывает конструктор базового класса FileReader.
void textReader::read_nbr(nbr &data)
Читает данные типа nbr из файла.
Читает данные из файла в формате NBR. data Ссылка на объект типа nbr для сохранения прочитанных данных. Функция read_nbr() читает данные типа nbr из файла и сохраняет их в объекте data. data ссылка на структуру nbr, в которую будут записаны данные из файла std::runtime_error в случае ошибки открытия файла
References FileReader::file_path_, nbr::icon.
void textReader::read_point(point &data)
Читает данные типа point из файла.
Читает данные из файла в формате точки data Ссылка на объект типа point для сохранения прочитанных данных. Функция read_point() читает данные типа point из файла и сохраняет их в объекте data. data ссылка на структуру point, в которую будут записаны данные из файла std::runtime_error в случае ошибки открытия файла
References point::coordinates, FileReader::file_path_.
Referenced by main.
void textReader::read_tbl(tbl &data)
Читает данные типа tbl из файла.
Читает данные из файла в формате TBL. data Ссылка на объект типа tbl для сохранения прочитанных данных. Функция read_tbl() читает данные типа tbl из файла и сохраняет их в объекте data. data ссылка на структуру tbl, в которую будут записаны данные из файла std::runtime_error в случае ошибки открытия файла или если не удается извлечь число из имени файла
References FileReader::file_path_, tbl::measurements, tbl::model, tbl::position, FileReader::readLineString.
Referenced by main.
void textReader::read_cfm(cfm &data)
Читает данные типа cfm из файла.
Читает данные из файла в формате CFM. data Ссылка на объект типа cfm для сохранения прочитанных данных. Функция read_cfm() читает данные типа cfm из файла и сохраняет их в объекте data. data ссылка на структуру cfm, в которую будут записаны данные из файла std::runtime_error в случае ошибки открытия файла
References cfm::big_tick, cfm::blank, cfm::diameter, cfm::digit_height, cfm::digital_tick, FileReader::file_path_, cfm::format, cfm::header, cfm::label_height, cfm::marks, cfm::small_tick, cfm::tick_mask, FileReader::trim.
Referenced by main.
void textReader::read_zgt(zgt &data)
Читает данные типа zgt из файла.
Читает данные из файла в формате ZGT. data Ссылка на объект типа zgt для сохранения прочитанных данных. Функция read_zgt() читает данные типа zgt из файла и сохраняет их в объекте data. data ссылка на структуру zgt, в которую будут записаны данные из файла std::runtime_error в случае ошибки открытия файла
References zgt::center_hole_diameter, zgt::diameter, FileReader::file_path_, zgt::font_serial_number, zgt::marker_position, zgt::mounting_holes, zgt::stop_position.
Referenced by main.