RenderPDF
const double RenderPDF::PI
Значение числа Пи
Referenced by generate_Marks.
double RenderPDF::margitText
Отступ для текста
bool RenderPDF::new_page
Флаг новой страницы
Referenced by generatePDF, RenderPDF.
std::filesystem::path RenderPDF::fontPath_
Путь к файлу шрифта
Referenced by generatePDF, initializeData, RenderPDF.
HPDF_Doc RenderPDF::pdf_
Документ PDF
Referenced by createA3Page, generatePDF, loadFont, ~RenderPDF.
HPDF_Font RenderPDF::font_
Шрифт PDF
Referenced by generatePDF, RenderPDF, setFontSize.
cfm RenderPDF::cfm_data_
Данные типа cfm
Referenced by adjustFontSize, calculateXCoordinate, calculateYCoordinate, drawAdditionalTicks, drawDigitIndices, drawMainLines, formatText, generatePDF, initializeData.
zgt RenderPDF::zgt_data_
Данные типа zgt
Referenced by generatePDF, initializeData.
nbr RenderPDF::nbr_data_
Данные типа nbr
Referenced by initializeData.
point RenderPDF::point_data_
Данные типа point
Referenced by calculateXCoordinate, calculateYCoordinate, checkForNewPage, drawAdditionalTicks, drawMainLines, generatePDF, initializeData.
std::vector<tbl> RenderPDF::tbl_data_
Вектор данных типа tbl
Referenced by generate_Marks, initializeData, populatePointTbl, sortTblData.
std::vector<size_t> RenderPDF::point_tbl
Таблица точек
Referenced by calculateXCoordinate, calculateYCoordinate, drawAdditionalTicks, drawMainLines, generatePDF, populatePointTbl.
std::vector<double> RenderPDF::marks
Метки
Referenced by drawAdditionalTicks, drawDigitIndices, drawMainLines, generate_Marks, generatePDF.
HPDF_Font RenderPDF::loadFont(const std::string &fontPath)
Загружает шрифт из указанного файла.
fontPath Путь к файлу шрифта. Возвращает объект HPDF_Font. std::runtime_error если не удается загрузить шрифт.
References pdf_.
Referenced by generatePDF, RenderPDF.
void RenderPDF::sortTblData()
Сортирует данные в tbl_data_ по положению элементов.
Эта функция использует стандартную функцию сортировки из библиотеки алгоритмов STL и лямбда-функцию для сравнения положения элементов.
References tbl::position, tbl_data_.
Referenced by RenderPDF.
void RenderPDF::populatePointTbl()
Заполняет point_tbl данными из tbl_data_.
Эта функция используется для копирования данных о позициях из tbl_data_ в point_tbl.
References point_tbl, tbl_data_.
Referenced by RenderPDF.
bool RenderPDF::checkForNewPage()
Проверяет наличие дубликатов координат в point_data_.
Возвращает true, если есть дубликаты координат, указывающие на необходимость новой страницы, иначе false.
References point::coordinates, point_data_.
Referenced by RenderPDF.
void RenderPDF::createA3Page()
Создает новую страницу формата A3.
References pdf_.
Referenced by generatePDF.
void RenderPDF::setFontSize(HPDF_Page page, double size)
Устанавливает размер шрифта и размер страницы PDF.
page Страница PDF, для которой нужно установить размер шрифта и размеры страницы. size Размер шрифта для установки.
References font_.
Referenced by drawDigitIndices.
void RenderPDF::generate_Marks(size_t blank)
Генерирует маркеры на основе измерений из данных таблицы.
blank Индекс строки в таблице данных, из которой следует сгенерировать маркеры.
References marks, PI, tbl_data_.
Referenced by generatePDF.
void RenderPDF::drawDigitIndices(HPDF_Page page, size_t blank)
Рисует индексы (цифры) на PDF странице.
page Страница PDF, на которую будут нарисованы индексы. blank Размер пустого пространства на странице.
References calculateXCoordinate, calculateYCoordinate, cfm_data_, cfm::digit_height, drawText, formatText, marks, setFontSize.
Referenced by generatePDF.
void RenderPDF::drawMainLines(HPDF_Page page, size_t blank)
Рисует основные линии на странице PDF.
page Страница PDF, на которой будут нарисованы основные линии. blank Индекс строки в таблице данных, на основе которой следует рисовать линии.
References cfm_data_, point::coordinates, cfm::diameter, cfm::digital_tick, draw_line, marks, point_data_, point_tbl.
Referenced by generatePDF.
void RenderPDF::drawAdditionalTicks(HPDF_Page page, size_t blank)
Рисует дополнительные отметки на странице PDF.
page Страница PDF, на которой будут нарисованы дополнительные отметки. blank Индекс строки в таблице данных, на основе которой следует рисовать отметки.
References cfm::big_tick, cfm_data_, point::coordinates, cfm::diameter, cfm::digital_tick, draw_line, marks, point_data_, point_tbl, cfm::small_tick, cfm::tick_mask.
Referenced by generatePDF.
void RenderPDF::initializeData(cfm cfm_data, zgt zgt_data, const std::vector< tbl > &tbl_data, nbr nbr_data, point point_data, std::filesystem::path fontPath)
Инициализирует данные.
cfm_data Данные для cfm. zgt_data Данные для zgt. tbl_data Данные для tbl. nbr_data Данные для nbr. point_data Данные для точки. fontPath Путь к файлу шрифта.
References cfm_data_, fontPath_, nbr_data_, point_data_, tbl_data_, zgt_data_.
Referenced by RenderPDF.
void RenderPDF::initializePDF()
Инициализирует объект HPDF_Doc для работы с PDF.
std::runtime_error если не удается создать объект PDF.
Referenced by RenderPDF.
void RenderPDF::adjustFontSize()
Подгоняет размер шрифта.
Использует коэффициент поправки размера для шрифта GOST_B.
References cfm_data_, cfm::digit_height.
Referenced by RenderPDF.
HPDF_REAL RenderPDF::calculateYCoordinate(HPDF_REAL angle, size_t blank)
Вычисляет координату Y для текста маркера.
angle Угол маркера. blank Размер пустого пространства на странице. Координата Y для текста маркера.
References cfm_data_, point::coordinates, cfm::diameter, cfm::digit_height, cfm::digital_tick, point_data_, point_tbl.
Referenced by drawDigitIndices.
HPDF_REAL RenderPDF::calculateXCoordinate(HPDF_REAL angle, double textWidth, size_t blank)
Вычисляет координату X для текста маркера.
angle Угол маркера. textWidth Ширина текста маркера. blank Размер пустого пространства на странице. Координата X для текста маркера.
References cfm_data_, point::coordinates, cfm::diameter, cfm::digital_tick, point_data_, point_tbl.
Referenced by drawDigitIndices.
std::string RenderPDF::formatText(int i)
Форматирует текст с использованием заданной точности.
i Индекс маркера, текст для которого нужно отформатировать. Отформатированный текст.
References cfm_data_, cfm::format, cfm::marks.
Referenced by drawDigitIndices.
void RenderPDF::drawText(HPDF_Page page, const std::string &text, HPDF_REAL x, HPDF_REAL y)
Рисует текст на странице PDF.
page Страница PDF, на которой будет нарисован текст. text Текст для вывода на страницу. x Координата X, где будет нарисован текст. y Координата Y, где будет нарисован текст.
Referenced by drawDigitIndices.
void RenderPDF::drawCircle(HPDF_Page page, double x, double y, double radius)
Рисует круг на странице PDF.
page Страница PDF, на которой будет нарисован круг. x Координата X центра круга. y Координата Y центра круга. radius Радиус круга.
Referenced by generatePDF.
void RenderPDF::draw_line(HPDF_Page page, HPDF_REAL x1, HPDF_REAL y1, HPDF_REAL x2, HPDF_REAL y2)
Рисует линию на странице PDF.
page Страница PDF, на которой будет нарисована линия. x1 Координата X начала линии. y1 Координата Y начала линии. x2 Координата X конца линии. y2 Координата Y конца линии.
Referenced by drawAdditionalTicks, drawMainLines.
void RenderPDF::generatePDF(std::string &filename)
Создает PDF-документ, используя графические элементы, определенные в других методах класса.
filename Ссылка на строку, содержащую имя будущего файла PDF. Если будет создано несколько страниц, то функция модифицирует эту строку, добавляя номер каждой страницы. Она создает страницы формата A3 и на каждой странице рисует набор элементов, таких как основные линии, индексы и дополнительные отметки, для каждого элемента в таблице точек (point_tbl). Генерация этих элементов осуществляется с помощью функций generate_Marks, drawMainLines, drawDigitIndices и drawAdditionalTicks. Эти функции используют данные из других членов класса, таких как cfm_data_ и zgt_data_. В конце, документ сохраняется в файл с указанным именем.
References zgt::center_hole_diameter, cfm_data_, point::coordinates, createA3Page, cfm::diameter, zgt::diameter, cfm::digital_tick, drawAdditionalTicks, drawCircle, drawDigitIndices, drawMainLines, font_, fontPath_, generate_Marks, loadFont, marks, zgt::mounting_holes, new_page, pdf_, point_data_, point_tbl, zgt_data_.
Referenced by main.
RenderPDF::RenderPDF(cfm cfm_data, zgt zgt_data, const std::vector< tbl > &tbl_data, nbr nbr_data, point point_data, std::filesystem::path fontPath)
Конструктор класса RenderPDF.
Инициализирует данные, создает объект PDF, подгоняет размер шрифта, загружает шрифт, сортирует данные таблицы и заполняет таблицу точек.
References adjustFontSize, checkForNewPage, font_, fontPath_, initializeData, initializePDF, loadFont, new_page, populatePointTbl, sortTblData.
RenderPDF::~RenderPDF()
Деструктор класса RenderPDF.
Освобождает ресурсы, связанные с объектом HPDF_Doc.
References pdf_.