.TH "CommandLine.h" 3Blanks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandLine.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBCommandLine\fP"
.br
.RI "Класс, представляющий интерфейс командной строки\&. "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Blanks из исходного текста\&.
