.TH "EncodingConverter.h" 3Blanks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EncodingConverter.h
.SH SYNOPSIS
.br
.PP
\fC#include 'string'\fP
.br
\fC#include 'vector'\fP
.br
\fC#include 'filesystem'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBEncodingConverter\fP"
.br
.RI "Класс для преобразования кодировки файлов\&. "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Blanks из исходного текста\&.
