.TH "FileReader.h" 3Blanks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileReader.h
.SH SYNOPSIS
.br
.PP
\fC#include <filesystem>\fP
.br
\fC#include <utility>\fP
.br
\fC#include 'string'\fP
.br
\fC#include 'fstream'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBFileReader\fP"
.br
.RI "Класс для чтения файла\&. "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Blanks из исходного текста\&.
