.TH "Generated.h" 3Blanks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Generated.h
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include 'nlohmann/json\&.hpp'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBGenerated\fP"
.br
.RI "Класс, содержащий функцию для генерации JSON-файла\&. "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Blanks из исходного текста\&.
