.TH "json.h" 3Blanks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
json.h
.SH SYNOPSIS
.br
.PP
\fC#include <nlohmann/json\&.hpp>\fP
.br
\fC#include 'ParserConfiguration\&.h'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBjson\fP"
.br
.RI "Класс для работы с JSON-конфигурацией\&. "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Blanks из исходного текста\&.
