.TH "nbr.h" 3Blanks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nbr.h
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "struct \fBnbr\fP"
.br
.RI "Структура для хранения данных типа nbr\&. "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Blanks из исходного текста\&.
