.TH "nbr" 3Blanks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nbr \- Структура для хранения данных типа nbr\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'nbr\&.h'\fP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "std::map< size_t, std::string > \fBicon\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Структура для хранения данных типа nbr\&. 

Структура nbr содержит поле для хранения отображения иконок в виде ассоциативного контейнера std::map\&. Ключом является размер иконки, а значением - строка, представляющая иконку\&. 
.PP
См\&. определение в файле \fBnbr\&.h\fP строка \fB14\fP
.SH "Данные класса"
.PP 
.SS "std::map<size_t, std::string> nbr::icon"
Контейнер для хранения иконок 
.PP
См\&. определение в файле \fBnbr\&.h\fP строка \fB15\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для Blanks из исходного текста\&.
