.TH "ParserConfiguration.h" 3Blanks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParserConfiguration.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <filesystem>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBParserConfiguration\fP"
.br
.RI "Класс для создания объекта конфигурации парсера\&. "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Blanks из исходного текста\&.
