.TH "Plug.h" 3Blanks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Plug.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'ParserConfiguration\&.h'\fP
.br
\fC#include 'json\&.h'\fP
.br

.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBparser\fP"
.br
.in -1c
.SS "Функции"

.in +1c
.ti -1c
.RI "static std::unique_ptr< \fBParserConfiguration\fP > \fBparser::create\fP (const std::string &config_file_path)"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Blanks из исходного текста\&.
