.TH "point_data.h" 3Blanks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
point_data.h
.SH SYNOPSIS
.br
.PP
\fC#include 'iostream'\fP
.br
\fC#include <vector>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "struct \fBpoint\fP"
.br
.RI "Структура для хранения координат точек\&. "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Blanks из исходного текста\&.
