.TH "textReader.cpp" 3Blanks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textReader.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./\&.\&./include/Reader/textReader\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <regex>\fP
.br

.SH "Автор"
.PP 
Автоматически создано Doxygen для Blanks из исходного текста\&.
