.TH "textReader.h" 3Blanks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textReader.h
.SH SYNOPSIS
.br
.PP
\fC#include <regex>\fP
.br
\fC#include 'FileReader\&.h'\fP
.br
\fC#include '\&.\&./struct/nbr\&.h'\fP
.br
\fC#include '\&.\&./struct/point_data\&.h'\fP
.br
\fC#include '\&.\&./struct/tbl\&.h'\fP
.br
\fC#include '\&.\&./struct/cfm\&.h'\fP
.br
\fC#include '\&.\&./struct/zgt\&.h'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBtextReader\fP"
.br
.RI "Класс для чтения текстового файла\&. "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Blanks из исходного текста\&.
